# Unit Notes and Homework (Day 7)
> "Libraries and Random Values"
 
- title: Unit Notes and Homework (Day 7)
- toc: true
- branch: master
- badges: true
- comments: true
- permalink: /jupyter/lesson7
- categories: [Lesson]

<style>
    .coolCode {
        color: #FFFFFF;
        font-family: monospace;
        border: 1px solid #404040;
        border-radius: 3px;
        background-color: #212121;
        padding: 1px 5px;
        font-size: 20px
    }
</style>

# Libraries

* A library is a collection of precompiled codes that can be used later on in a program for some specific well-defined operations. 
* These precompiled codes can be referred to as modules. Each module contains bundles of code that can be used repeatedly in different programs.
* A library may also contain documentation, configuration data, message templates, classes, and values, etc.

### Why are libraries important?
* Using Libraries makes Python Programming simpler and convenient for the programmer. 
* One example would be through looping and iteration, as we don’t need to write the same code again and again for different programs. 
* Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

### A few libraries that simplify coding processes:
* **Pillow** allows you to work with images.
* **Tensor Flow** helps with data automation and monitors performance.
* **Matplotlib** allows you to make 2D graphs and plots.

The AP Exam Refrence Sheet itself is a library!
![Screenshot 2022-12-11 221853](https://user-images.githubusercontent.com/51098969/206974627-af98327c-d95d-4459-be67-cbaa3faaaa98.jpg)

## Hacks:
Research two other Python Libraries NOT DISCUSSED DURING LESSON and make a markdown post, explaining their function and how it helps programmers code.

### API’s
* An Application Program Interface, or API, contains specific direction for how the procedures in a library behave and can be used. 
* An API acts as a gateway for the imported procedures from a library to interact with the rest of your code.

### Activity: Walkthrough with NumPy
* Install NumPy on VSCode:
    1. Open New Terminal In VSCode:
    2. pip3 install --upgrade pip
    3. pip install numpy 
 
REMEMBER: When running library code cells use Python Interpreter Conda (Version 3.9.12)
 
### Example of using NumPy for arrays:

In [1]:
import numpy as np
new_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
 
print (new_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Example of using NumPy for derivatives:

In [2]:
import numpy as np
 
# defining polynomial function
var = np.poly1d([2, 0, 1])
print("Polynomial function, f(x):\n", var)
 
# calculating the derivative
derivative = var.deriv()
print("Derivative, f(x)'=", derivative)
 
# calculates the derivative of after
# given value of x
print("When x=5  f(x)'=", derivative(5))

Polynomial function, f(x):
    2
2 x + 1
Derivative, f(x)'=  
4 x
When x=5  f(x)'= 20


## Random Values

* Random number generation (RNG) produces a random number (crazy right?)
    - This means that a procedure with RNG can return different values even if the parameters (inputs) do not change
* CollegeBoard uses <code class="coolCode">RANDOM(A, B)</code>, to return an integer between integers <code class="coolCode">A</code> and <code class="coolCode">B</code>.
    - RANDOM(1, 10) can output 1, 2, 3, 4, 5, 6, 7, 8, 9, or 10
    - In Python, this would be <code class="coolCode">random.randint(A, B)</code>, after importing Python's "random" library (<code class="coolCode">import random</code>)
    - JavaScript's works a little differently, with <code class="coolCode">Math.random()</code> returning a value between 0 and 1.
        - To match Python and CollegeBoard, you could make a procedure like [this](https://stackoverflow.com/a/7228322)

#### CollegeBoard Example: What is the possible range of values for *answ3*
![CollegeBoard](https://i.ibb.co/Wt90Hbz/Screen-Shot-2022-12-12-at-7-27-58-AM.png)


#### Convert the following procedure to Python, then determine the range of outputs if n = 5.
<pre>
<font color=white>
PROCEDURE Dice(n)
	sum ← 0
	REPEAT UNTIL n = 0
		sum ← sum + RANDOM(1, 6)
		n ← n - 1
	RETURN sum
</font>
</pre>


In [2]:
import random

def Dice(n):
    sum = 0
    while n > 0:
        sum = sum + random.randint(1, 6)
        n = n - 1 
    return sum
    
    
Dice(5) # Will output a sum of the 5 dice rolls

16

## Homework
1. Write a procedure that generates *n* random numbers, then sorts those numbers into lists of even and odd numbers (JS or Python, Python will be easier).

2. Using NumPy and only coding in python cell, find the answer to the following questions:
    a. What is the derivative of 2x^5 - 6x^2 + 24x?
    b. What is the derivative of (13x^4 + 4x^2) / 2 when x = 9? 

3. Suppose you have a group of 10 dogs and 10 cats, and you want to create a random order for them. Show how random number generation could be used to create this random order.

In [5]:
import random

def grn(n):
    numbers = []
    for i in range(n):
        numbers.append(random.randint(1, 101))
    even = []
    odd = []
    for x in numbers:
        if x % 2 == 0:
            even.append(x)
        else:
            odd.append(x)
    return even, odd
    
even , odd = grn(100)

print("Odd:" , *odd)
print("Even:" , *even)

Odd: 17 33 63 7 67 55 41 35 9 11 19 83 15 13 39 1 21 7 101 83 45 13 11 39 53 3 41 77 7 65 71 63 33 63 17 69 77 91 35 57 47 29 83
Even: 24 84 2 26 30 52 44 62 76 76 96 38 30 6 52 92 4 12 10 2 48 4 24 84 74 40 18 4 38 48 66 10 76 50 80 56 36 34 64 20 32 22 44 48 76 90 60 42 66 98 2 84 98 40 90 40 36


In [7]:
import numpy as np

# Define the polynomial
poly = np.poly1d([2, 0, 0, 6, 24, 0])

# Calculate the derivative
deriv = np.polyder(poly)

# Print the derivative
print(deriv)

    4
10 x + 12 x + 24


In [13]:
import numpy as np

# Define the polynomial
poly = np.poly1d([6.5, 0, 2, 0, 0])

# Calculate the derivative
deriv = np.polyder(poly)

# Print the derivative
print(deriv)

# when x = 9
print("When x=9  f'(x)=", deriv(9))

    3
26 x + 4 x
When x=9  f'(x)= 18990.0


In [15]:
import random

# Create a list containing the names of the dogs and cats. For example:
animals = ['dog1', 'dog2', 'dog3', 'dog4', 'dog5', 'dog6', 'dog7', 'dog8', 'dog9', 'dog10', 'cat1', 'cat2', 'cat3', 'cat4', 'cat5', 'cat6', 'cat7', 'cat8', 'cat9', 'cat10']

# Use the random.shuffle() function to shuffle the list of animals in place
random.shuffle(animals)

# Print the shuffled list of animals to see the new random order
print(animals)

# This will produce a random order for the dogs and cats

['cat10', 'dog8', 'cat6', 'cat7', 'dog9', 'dog1', 'cat4', 'cat2', 'dog3', 'dog4', 'dog10', 'dog2', 'cat3', 'cat9', 'cat8', 'cat5', 'dog7', 'cat1', 'dog6', 'dog5']
